/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/categories': RouteRecordInfo<
      '/admin/categories',
      '/admin/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/posts/': RouteRecordInfo<
      '/admin/posts/',
      '/admin/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/posts/[id]': RouteRecordInfo<
      '/admin/posts/[id]',
      '/admin/posts/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/admin/posts/new': RouteRecordInfo<
      '/admin/posts/new',
      '/admin/posts/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/settings': RouteRecordInfo<
      '/admin/settings',
      '/admin/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/tags': RouteRecordInfo<
      '/admin/tags',
      '/admin/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/users': RouteRecordInfo<
      '/admin/users',
      '/admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives': RouteRecordInfo<
      '/archives',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/banned': RouteRecordInfo<
      '/banned',
      '/banned',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/[slug]': RouteRecordInfo<
      '/categories/[slug]',
      '/categories/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/moments': RouteRecordInfo<
      '/moments',
      '/moments',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/[slug]': RouteRecordInfo<
      '/posts/[slug]',
      '/posts/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/tags/[slug]': RouteRecordInfo<
      '/tags/[slug]',
      '/tags/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/about.vue': {
      routes:
        | '/about'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/categories.vue': {
      routes:
        | '/admin/categories'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/posts/index.vue': {
      routes:
        | '/admin/posts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/posts/[id].vue': {
      routes:
        | '/admin/posts/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/admin/posts/new.vue': {
      routes:
        | '/admin/posts/new'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/settings.vue': {
      routes:
        | '/admin/settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/tags.vue': {
      routes:
        | '/admin/tags'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/users.vue': {
      routes:
        | '/admin/users'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/archives.vue': {
      routes:
        | '/archives'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/banned.vue': {
      routes:
        | '/banned'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/categories/[slug].vue': {
      routes:
        | '/categories/[slug]'
      views:
        | never
      pathParamNames:
        | 'slug'
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/moments.vue': {
      routes:
        | '/moments'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/posts/[slug].vue': {
      routes:
        | '/posts/[slug]'
      views:
        | never
      pathParamNames:
        | 'slug'
    }
    'src/pages/tags/[slug].vue': {
      routes:
        | '/tags/[slug]'
      views:
        | never
      pathParamNames:
        | 'slug'
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
